apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check-gcip
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check-gcip
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check-gcip
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check-gcip
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check-gcip
    spec:
      containers:
      - image: quay.io/quay_xjiang/rhtap-demo-ssfi-tenant/e2e-nodejs/nodejs-health-check-gcip@sha256:0da54ccd0494bc95700993664989bdd72a5f592f26f2e9caa11a1ab22d3469d7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
